export const mockData = [
  { value: "tom@pau.be", label: "tom@pau.be", disabled: false },
  { value: "wim@pau.be", label: "wim@pau.be", disabled: false },
  { value: "wouter@pau.be", label: "wouter@pau.be", disabled: false },
  { value: "willem@pau.be", label: "willem@pau.be", disabled: false },
  { value: "willem2@pau.be", label: "willem2@pau.be", disabled: true },
  { value: "kenneth@pau.be", label: "kenneth@pau.be", disabled: false },
  { value: "kevin@pau.be", label: "kevin@pau.be", disabled: false },
  { value: "jeroen@pau.be", label: "jeroen@pau.be", disabled: false },
  { value: "hendrik@pau.be", label: "hendrik@pau.be", disabled: false },
  { value: "arno@pau.be", label: "arno@pau.be", disabled: false },
  { value: "johan@pau.be", label: "johan@pau.be", disabled: false },
  { value: "john@pau.be", label: "john@pau.be", disabled: false },
  { value: "lenny@pau.be", label: "lenny@pau.be", disabled: false },
  { value: "jeroen@telenet.be", label: "jeroen@telenet.be", disabled: false },
  { value: "jeroen@gmail.com", label: "jeroen@gmail.com", disabled: false },
  { value: "jeroen@outlook.com", label: "jeroen@outlook.com", disabled: false },
  { value: "john@outlook.com", label: "john@outlook.com", disabled: false },
]
